=== eschult2001/Network-Poker-Clock/tournament.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		xmlns:tns="uri:dpclock:tournamentSettings" 
		targetNamespace="uri:dpclock:tournamentSettings" 
		elementFormDefault="unqualified">
	<element name="tournament" >
		<complexType>
			<all>
				<element name="name" 			type="string"/>
				<element name="startingLevel"	type="string" />
				<element name="levels">
					<complexType>
						<choice maxOccurs="unbounded">
							<element name="level">
								<complexType>
									<attribute name="name" type="string" />
									<attribute name="smallBlind" type="int" />
									<attribute name="bigBlind" type="int" />
									<attribute name="ante" type="int"/>
									<attribute name="seconds" type="int"/>
								</complexType>
							</element>
							<element name="break">
								<complexType>
									<sequence>
										<element name="note" type="string"/>
									</sequence>
									<attribute name="name" type="string" />
									<attribute name="seconds" type="int"/>
								</complexType>
							</element>
						</choice>
					</complexType>
				</element>
			</all>
		</complexType>
	</element>
</schema>

=== eschult2001/Network-Poker-Clock/tournament.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:tournament xmlns:ns2="uri:dpclock:tournamentSettings"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="uri:dpclock:tournamentSettings tournament.xsd">
	<name>MWPT Monthly Bounty Tourney</name>
	<startingLevel>Level 1</startingLevel>
	<levels>
		<level name="Level 1"	smallBlind="25"		bigBlind="50"		ante="0" 		seconds="900"/>
		<level name="Level 2"	smallBlind="50"		bigBlind="100"		ante="0" 		seconds="900"/>
		<level name="Level 3"	smallBlind="100"	bigBlind="200"		ante="0" 		seconds="900"/>
		<level name="Level 4"	smallBlind="100"	bigBlind="200"		ante="25" 		seconds="900"/>
		<level name="Level 5"	smallBlind="200"	bigBlind="400"		ante="50" 		seconds="900"/>
		<level name="Level 6"	smallBlind="300"	bigBlind="600"		ante="75" 		seconds="900"/>
		<break name="Break">
			<note>Chip-up 25s &amp; 50s</note>
		</break>	
		<level name="Level 7"	smallBlind="400"	bigBlind="800"		ante="100" 		seconds="900"/>
		<level name="Level 8"	smallBlind="600"	bigBlind="1200"		ante="200" 		seconds="900"/>
		<level name="Level 9"	smallBlind="800"	bigBlind="1600"		ante="300" 		seconds="900"/>
		<level name="Level 10"	smallBlind="1000"	bigBlind="2000"		ante="300" 		seconds="900"/>
		<level name="Level 11"	smallBlind="1500"	bigBlind="3000"		ante="500" 		seconds="900"/>
		<level name="Level 12"	smallBlind="2000"	bigBlind="4000"		ante="500" 		seconds="900"/>
		<break name="Break">
			<note>Chip-up 100s &amp; 500s</note>
		</break>	
		<break name="Break">
			<note>Chip-up 100s &amp; 500s</note>
		</break>	
		<level name="Level 13"	smallBlind="3000"	bigBlind="6000"		ante="1000" 	seconds="900"/>
		<level name="Level 14"	smallBlind="4000"	bigBlind="8000"		ante="1000" 	seconds="900"/>
		<level name="Level 15"	smallBlind="6000"	bigBlind="12000"	ante="2000" 	seconds="900"/>
		<level name="Level 16"	smallBlind="8000"	bigBlind="16000"	ante="3000" 	seconds="900"/>
		<level name="Level 17"	smallBlind="10000"	bigBlind="20000"	ante="3000" 	seconds="900"/>
		<level name="Level 18"	smallBlind="15000"	bigBlind="30000"	ante="5000" 	seconds="900"/>
		<break name="Break">
			<note>Chip-up 100s &amp; 500s</note>
		</break>
	</levels>
</ns2:tournament>

=== eschult2001/Network-Poker-Clock/Copy of tournament.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tournament 
	xmlns="uri:dpclock:tournamentSettings"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="uri:dpclock:tournamentSettings tournament.xsd">
	
	<name>MWPT</name>
	<startingLevel>Level 1</startingLevel>
	<leveltime>900</leveltime>
	<breaktime>0</breaktime>
	<levels>
		<level name="Level 1"	smallBlind="25"		bigBlind="50"		ante="0" 	/>
		<level name="Level 2"	smallBlind="50"		bigBlind="100"		ante="0" />
		<level name="Level 3"	smallBlind="100"	bigBlind="200"		ante="0" />
		<level name="Level 4"	smallBlind="100"	bigBlind="200"		ante="25" />
		<level name="Level 5"	smallBlind="200"	bigBlind="400"		ante="50" />
		<level name="Level 6"	smallBlind="300"	bigBlind="600"		ante="75" />
		<break name="Break 1">
			<note>Chip-up 25s &amp; 50s</note>
		</break>	
		<level name="Level 7"	smallBlind="400"	bigBlind="800"		ante="100" />
		<level name="Level 8"	smallBlind="600"	bigBlind="1200"		ante="200" />
		<level name="Level 9"	smallBlind="800"	bigBlind="1600"		ante="300" />
		<level name="Level 10"	smallBlind="1000"	bigBlind="2000"		ante="300" />
		<level name="Level 11"	smallBlind="1500"	bigBlind="3000"		ante="500" />
		<level name="Level 12"	smallBlind="2000"	bigBlind="4000"		ante="500" />
		<break name="Break 1">
			<note>Chip-up 100s &amp; 500s</note>
		</break>	
		<level name="Level 13"	smallBlind="3000"	bigBlind="6000"		ante="1000" />
		<level name="Level 14"	smallBlind="4000"	bigBlind="8000"		ante="1000" />
		<level name="Level 15"	smallBlind="6000"	bigBlind="12000"	ante="2000" />
		<level name="Level 16"	smallBlind="8000"	bigBlind="16000"	ante="3000" />
		<level name="Level 17"	smallBlind="10000"	bigBlind="20000"	ante="3000" />
		<level name="Level 18"	smallBlind="15000"	bigBlind="30000"	ante="5000" />
	</levels>
</tournament>
